#!/bin/bash

#docker buildx create --name aixp-builder --bootstrap --use
#docker buildx build --platform linux/arm64/v8 --push -t $IMAGE_NAME .

docker buildx create --name aixp-builder --use
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
docker buildx use aixp-builder
docker buildx inspect --bootstrap
docker buildx build --platform linux/arm/v8 -t $IMAGE_NAME --push .
