FROM nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3

RUN git clone git://source.ffmpeg.org/ffmpeg.git

WORKDIR /ffmpeg

RUN ./configure

RUN make

RUN make install

WORKDIR /exe_eng

COPY . /exe_eng

RUN pip install --no-cache-dir --upgrade -r requirements_tegra.txt

# Install tzdata if it's not available in your base image. 
RUN apt-get update && apt-get install -y tzdata nano vim

# Use the TZ variable to set the timezone
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# set a generic env variable 
ENV AIXP_DOCKER Yes
ENV AIXP_ENV v0.5-2.0.1-tegra
