FROM arm64v8/ubuntu:22.04 

ENV AIXP_DOCKER Yes
ENV AIXP_ENV v0.8-2.1

RUN apt update --quiet && apt upgrade -y && apt install -y python3 python3-dev python3-pip ffmpeg

WORKDIR /aixp-build
COPY ./requirements_rpi.txt .

RUN pip install -r requirements_rpi.txt
