FROM pytorch/pytorch

RUN conda update conda && \
  conda install -c conda-forge "transformers>=4.34.0" && \
  conda install seaborn pandas shapely scikit-learn scikit-image dropbox pymssql h5py unidecode && \
  conda install -c conda-forge "ffmpeg>=5"

WORKDIR /exe_eng_base
COPY . /exe_eng_base

# after copy run requirements
RUN pip install --no-cache-dir --upgrade -r requirements.txt && \
  pip install --no-cache-dir tensorrt --extra-index-url https://pypi.nvidia.com && \
  pip install --no-cache-dir onnx onnxsim

# Set a default value for the TZ environment variable
ENV TZ=Europe/Bucharest

# Install ip-utils for debugging connection.
# Additionally install tzdata if it's not available in your base image.
RUN apt-get update && apt-get install -y iputils-ping tzdata nano vim

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# set a generic env variable
ENV AIXP_DOCKER Yes
ENV AIXP_ENV v0.8-3.0

